// Ignore Spelling: Utils
//

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.IO.IsolatedStorage;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Formatters.Binary;
using PK.PkUtils.DataStructures;
using PK.PkUtils.Extensions;
using PK.PkUtils.Interfaces;
using static System.FormattableString;

namespace PK.PkUtils.IO;

#pragma warning disable SYSLIB0011 // BinaryFormatter serialization is obsolete and should not be used.

/// <summary>
/// Provides a dictionary-based persistent application store backed by
/// <see cref="IsolatedStorageFile"/>.
/// </summary>
///
/// <remarks>
/// <para>
/// <b>Purpose and alternatives</b><br/>
/// Applications often need to persist settings or other small pieces of state between runs. Modern .NET
/// applications commonly use configuration providers (for example JSON configuration) for declarative
/// configuration. Configuration files are convenient when settings are expected to be supplied or edited
/// outside the application, but they are not always the best fit for application-managed, per-user state.
/// Other possible persistence mechanisms include ordinary files, the Windows Registry, databases,
/// and serialization of custom objects.
/// </para>
/// <para>
/// This class uses isolated storage. Isolated storage provides a file-system-like store whose physical
/// location is managed by .NET and whose identity is determined by the requested
/// <see cref="IsolatedStorageScope"/>. Code using this class therefore does not need to construct a physical
/// path for the persisted data. The default scope used by <see cref="ApplicationStorage{T}()"/> is
/// <see cref="IsolatedStorageScope.User"/> combined with <see cref="IsolatedStorageScope.Assembly"/>.
/// </para>
/// <para>
/// <b>ApplicationStorage overview</b><br/>
/// <see cref="ApplicationStorage{T}"/> derives from <see cref="Dictionary{TKey,TValue}"/> and stores values
/// under string keys. Unless a constructor intended only to initialize values is used, construction loads
/// previously persisted data by calling <see cref="LoadData"/> or <see cref="SafeLoadData"/>.
/// Calling <see cref="Save"/> serializes the dictionary to a file in the selected isolated store.
/// The file name is generated by <see cref="GenerateSettingsFileName"/> and can be customized 
/// by supplying a suffix or by overriding that method.
/// </para>
/// <para>
/// <b>Failure handling</b><br/>
/// Normal loading can propagate isolated-storage or serialization-related exceptions. When safe loading is
/// requested, <see cref="SafeLoadData"/> catches the supported load failures and reports the result through
/// <see cref="LastSafeLoadResult"/> instead. <see cref="LastLoadFoundAnyStorage"/> indicates whether the last
/// load found the expected settings file; it does not indicate that deserialization succeeded.
/// </para>
/// <para>
/// <b>Thread safety</b><br/>
/// This class inherits the thread-safety characteristics of <see cref="Dictionary{TKey,TValue}"/>. 
/// Concurrent reads are safe only while the collection is not being modified. If multiple threads can read 
/// and write the same instance, callers must provide synchronization or use a different data structure designed for
/// concurrent access, such as <see cref="System.Collections.Concurrent.ConcurrentDictionary{TKey,TValue}"/>.
/// </para>
/// <para>
/// <b>Persistence and security considerations</b><br/>
/// Isolated storage is an organization and isolation mechanism, not a security boundary for sensitive data.
/// A user or process with sufficient access to the user's profile or machine storage can potentially delete,
/// replace, or corrupt the stored file. Applications must therefore validate loaded values as appropriate and
/// must not rely on isolated storage as encryption or tamper protection.
/// </para>
/// <para>
/// This implementation currently persists data using <see cref="BinaryFormatter"/> for compatibility with
/// existing stored data. Since <see cref="BinaryFormatter"/> is obsolete and insecure; Microsoft recommends that
/// applications migrate away from it. Starting with .NET 9, the runtime no longer contains a working
/// <see cref="BinaryFormatter"/> implementation. This project therefore relies on the unsupported
/// <c>System.Runtime.Serialization.Formatters</c> compatibility package to retain the legacy behavior.
/// Serialized data must be treated as trusted application data only. A future persistence-format migration
/// should take backward compatibility with existing <c>.dtt</c> files into account.
/// </para>
/// <para>
/// <b>Dictionary behavior</b><br/>
/// Earlier versions of this utility used a non-generic hash table. The current implementation derives from
/// <see cref="Dictionary{TKey,TValue}"/>. In particular, indexing a missing key throws
/// <see cref="KeyNotFoundException"/>; use <see cref="Dictionary{TKey,TValue}.TryGetValue"/> when absence is
/// expected. The generic dictionary also does not make concurrent read/write access safe automatically.
/// </para>
/// <para>
/// <b>Further reference</b><br/>
/// Microsoft documentation:<br/>
/// Isolated storage: https://learn.microsoft.com/dotnet/standard/io/isolated-storage <br/>
/// <see cref="IsolatedStorageScope"/>: https://learn.microsoft.com/dotnet/api/system.io.isolatedstorage.isolatedstoragescope <br/>
/// <see cref="IsolatedStorageFile"/>: https://learn.microsoft.com/dotnet/api/system.io.isolatedstorage.isolatedstoragefile <br/>
/// .NET configuration: https://learn.microsoft.com/dotnet/core/extensions/configuration <br/>
/// BinaryFormatter security guide: https://learn.microsoft.com/dotnet/standard/serialization/binaryformatter-security-guide <br/>
/// BinaryFormatter migration guide: https://learn.microsoft.com/dotnet/standard/serialization/binaryformatter-migration-guide/ <br/>
/// </para>
/// </remarks>
///
/// <typeparam name="T">The type of values stored in the persistent dictionary.</typeparam>
[Serializable]
public class ApplicationStorage<T> : Dictionary<string, T>
{
    #region Fields

    /// <summary> The default isolated-storage scope used by the parameterless constructor. </summary>
    [NonSerialized]
    public const IsolatedStorageScope DefaultStorageScope = IsolatedStorageScope.User | IsolatedStorageScope.Assembly;

    /// <summary> Result of the most recent call to <see cref="SafeLoadData"/>. </summary>
    [NonSerialized]
    private IComplexResult _lastSafeLoadResult;

    /// <summary> Indicates whether the most recent load found the expected storage file. </summary>
    [NonSerialized]
    private bool _lastLoadFoundAnyStorage;

    /// <summary> Scope of the isolated storage, as provided by the constructor.</summary>
    /// <remarks> Typically includes <see cref="IsolatedStorageScope.User"/>, <see cref="IsolatedStorageScope.Assembly"/>, or both. </remarks>
    [NonSerialized]
    private readonly IsolatedStorageScope _scope;

    /// <summary>
    /// File name within isolated storage. It is generated from the resolved assembly name, an optional suffix, and the <c>.dtt</c> extension.
    /// </summary>
    private readonly string _settingsFileName;
    #endregion // Fields

    #region Constructor(s)

    /// <summary>
    /// The default data-loading constructor. Creates a new <see cref="ApplicationStorage{T}"/> instance. 
    /// It also loads persisted data by calling <see cref="LoadData"/>. 
    /// It may throw <see cref="IsolatedStorageException"/>, <see cref="SerializationException"/>
    /// or <see cref="TargetInvocationException"/>, in case called method LoadData() throws that exception.
    /// </summary>
    /// 
    /// <exception cref="SerializationException"> Thrown if called LoadData throws that exception. </exception>
    public ApplicationStorage()
        : this(DefaultStorageScope, false)
    { }

    /// <summary>
    /// A "data loading" constructor, delegating the call to overloaded constructor <see cref="ApplicationStorage{T}(IsolatedStorageScope, bool, string)"/>
    /// which loads the data ( passing to it the <paramref name="safeLoad"/>argument ).
    /// </summary>
    /// <exception cref="IsolatedStorageException"> Thrown if called LoadData throws that exception. </exception>
    /// <exception cref="SerializationException"> Thrown if called LoadData throws that exception. </exception>
    /// <exception cref="TargetInvocationException"> Thrown if called LoadData throws that exception. </exception>
    /// 
    /// <param name="safeLoad"> If this value is false, the constructor calls <see cref="LoadData"/>, otherwise
    /// it calls <see cref="SafeLoadData"/>. </param>
    public ApplicationStorage(bool safeLoad)
      : this(DefaultStorageScope, safeLoad)
    { }

    /// <summary>
    /// A "data loading" constructor, delegating the call to overloaded constructor <see cref="ApplicationStorage{T}(IsolatedStorageScope, bool, string)"/>
    /// which loads the data ( passing to it the <paramref name="safeLoad"/>argument ).
    /// </summary>
    /// <exception cref="IsolatedStorageException"> Thrown if called LoadData throws that exception. </exception>
    /// <exception cref="SerializationException"> Thrown if called LoadData throws that exception. </exception>
    /// <exception cref="TargetInvocationException"> Thrown if called LoadData throws that exception. </exception>
    /// 
    /// <param name="scope"> Scope of underlying isolated storage. </param>
    /// <param name="safeLoad"> If this value is false, the constructor calls <see cref="LoadData"/>, otherwise
    /// it calls <see cref="SafeLoadData"/>. </param>
    public ApplicationStorage(IsolatedStorageScope scope, bool safeLoad)
      : this(scope, safeLoad, string.Empty)
    { }

    /// <summary>
    /// A "data loading" constructor, accepting a file name suffix to be used by the called <see cref="GenerateSettingsFileName"/>method.
    /// Depending on the argument <paramref name="safeLoad"/> value, the constructor calls either
    /// <see cref="LoadData"/> or <see cref="SafeLoadData"/>. <br/>
    /// <see cref="SafeLoadData"/> handles the supported load failures without throwing them and reports the result through <see cref="LastSafeLoadResult"/>.
    ///
    /// </summary>
    /// 
    /// <exception cref="IsolatedStorageException"> Thrown if called LoadData throws that exception. </exception>
    /// <exception cref="SerializationException"> Thrown if called LoadData throws that exception. </exception>
    /// <exception cref="TargetInvocationException"> Thrown if called LoadData throws that exception. </exception>
    ///
    /// <param name="scope"> Scope of underlying isolated storage. </param>
    /// <param name="safeLoad"> If this value is false, the constructor calls <see cref="LoadData"/>,
    /// otherwise it calls <see cref="SafeLoadData"/>. </param>
    /// 
    /// <param name="fileNameSuffix"> The file name suffix that will be used as an argument for
    /// <see cref="GenerateSettingsFileName"/> </param>
    public ApplicationStorage(IsolatedStorageScope scope, bool safeLoad, string fileNameSuffix)
    {
        _scope = scope;
        _settingsFileName = GenerateSettingsFileName(fileNameSuffix);

        if (!safeLoad)
        {
            LoadData();
        }
        else
        {
            SafeLoadData();
        }
    }

    /// <summary>
    /// A constructor that initializes a new instance of ApplicationStorage, that contains elements 
    /// copied from the specified IDictionary <paramref name="dictionary"/>.
    /// 
    /// The created instance can later be used to persist the data by calling <see cref="Save()"/>.
    /// Note this constructor does NOT call that method by itself. 
    /// </summary>
    /// 
    /// <exception cref="ArgumentNullException"> Thrown if required argument <paramref name="dictionary"/> is null.
    /// </exception>
    /// 
    /// <param name="scope"> Scope of underlying isolated storage. </param>
    /// <param name="dictionary"> The dictionary providing initial contents of ApplicationStorage, to be saved later. 
    ///                           Can't be null.
    /// </param>
    /// <param name="fileNameSuffix"> The file name suffix that will be used as an argument for
    /// <see cref="GenerateSettingsFileName"/> </param>
    public ApplicationStorage(IsolatedStorageScope scope, IDictionary<string, T> dictionary, string fileNameSuffix)
        : base(dictionary)
    {
        _scope = scope;
        _settingsFileName = GenerateSettingsFileName(fileNameSuffix);
    }

    /// <summary>
    /// This protected constructor supports deserialization of the dictionary from persistent storage
    /// when the object is binary-serialized through the <see cref="SerializableAttribute"/> mechanism.
    /// </summary>
    /// 
    /// <param name="info">The <see cref="SerializationInfo"/> containing the serialized object data.</param>
    /// <param name="context"> The StreamingContext that contains contextual information about the
    /// source or destination. </param>
    [Obsolete("This BinaryFormatter-compatible serialization API uses StreamingContext and is retained for legacy persistence compatibility.")]
    protected ApplicationStorage(SerializationInfo info, StreamingContext context)
        : base(info, context)
    {
        _settingsFileName = GenerateSettingsFileName(string.Empty);
    }
    #endregion // Constructor(s)

    #region Properties

    /// <summary> Gets the underlying isolated-storage scope provided to the constructor. </summary>        
    public IsolatedStorageScope Scope
    {
        get { return _scope; }
    }

    /// <summary>
    /// Has the last call of "safe load" failed?
    /// The value is set by <see cref="SafeLoadData"/>, and reset to null by <see cref="ResetContents"/>.
    /// </summary>
    public IComplexResult LastSafeLoadResult
    {
        get { return _lastSafeLoadResult; }
    }

    /// <summary> Gets a value indicating whether the last load found the expected file in isolated storage. </summary>
    public bool LastLoadFoundAnyStorage
    {
        get { return _lastLoadFoundAnyStorage; }
    }

    /// <summary> Gets the filename of the settings file. </summary>
    protected virtual string SettingsFileName
    {
        get { return _settingsFileName; }
    }
    #endregion // Properties

    #region Methods

    #region Public Methods

    /// <summary> Loads the data again from persistent storage. </summary>
    public void ReLoad()
    {
        LoadData();
    }

    /// <summary>
    /// Saves the data to the persistent storage.
    /// </summary>
    public void Save()
    {
        // Open the stream from the IsolatedStorage.
        IsolatedStorageFile isoStore = GetStorageFile();
        using Stream stream = new IsolatedStorageFileStream(SettingsFileName, FileMode.Create, isoStore);

        // Serialize the contents into the IsolatedStorage.
        BinaryFormatter formatter = new();
        formatter.Serialize(stream, this);
    }

    /// <summary>
    /// Clears the dictionary and resets <see cref="LastSafeLoadResult"/>.
    /// </summary>
    public void ResetContents()
    {
        Clear();
        _lastSafeLoadResult = null;
    }

    /// <summary> Supplies the data required to serialize this instance using the legacy binary-serialization mechanism. </summary>
    ///
    /// <param name="info">The object populated with the information required to serialize this instance.</param>
    /// 
    /// <param name="context">Context describing the source and destination of the serialized stream.</param>
    [Obsolete("This BinaryFormatter-compatible serialization API uses StreamingContext and is retained for legacy persistence compatibility.")]
    public override void GetObjectData(SerializationInfo info, StreamingContext context)
    {
        base.GetObjectData(info, context);
    }
    #endregion // Public Methods

    #region Protected methods

    /// <summary>
    /// Loads the data from underlying <see cref="IsolatedStorageFile"/> storage.
    /// The storage file name is obtained from <see cref="SettingsFileName"/>.
    /// </summary>
    protected virtual void LoadData()
    {
        IsolatedStorageFile isoStore;
        string fileName = SettingsFileName;

        _lastLoadFoundAnyStorage = false;
        isoStore = GetStorageFile();

        if (isoStore.GetFileNames(fileName).Length == 0)
        {
            // The file does not exist; do not attempt to deserialize it.
            return;
        }
        else
        {
            _lastLoadFoundAnyStorage = true;

            // Read the stream from Isolated Storage.
            using Stream stream = new IsolatedStorageFileStream(fileName, FileMode.OpenOrCreate, isoStore);

            // Deserialize the contents from the stream.
            BinaryFormatter formatter = new();
            Dictionary<string, T> appData = (Dictionary<string, T>)formatter.Deserialize(stream);

            // Enumerate through the collection and load our base dictionary.
            Dictionary<string, T>.Enumerator enumerator = appData.GetEnumerator();
            while (enumerator.MoveNext())
            {
                this[enumerator.Current.Key] = enumerator.Current.Value;
            }
        }
    }

    /// <summary>
    /// This is the "safe" version of <see cref="LoadData"/>.
    /// It handles supported load failures and reports the outcome through <see cref="LastSafeLoadResult"/>.
    /// </summary>
    protected void SafeLoadData()
    {
        Exception exCaught = null;

        try
        {
            LoadData();
            _lastSafeLoadResult = ComplexResult.OK;
        }
        catch (IsolatedStorageException ex) { exCaught = ex; }
        catch (SerializationException ex) { exCaught = ex; }
        catch (TargetInvocationException ex) when (ex.AllInnerExceptions().Any(x => x is SerializationException))
        {
            exCaught = ex;
        }


        if (exCaught != null)
        {
            string errorMessage = Invariant($"{nameof(SafeLoadData)} failed by {exCaught.GetType().Name} [{exCaught.Message}].");

            _lastSafeLoadResult = ComplexResult.CreateFailed(errorMessage, exCaught);
            Debug.WriteLine(errorMessage);
        }
    }

    /// <summary> Implementation helper that generates the settings file name.
    /// The result is used for <see cref="_settingsFileName"/> initialization.<br/> </summary>
    ///
    /// <remarks> You may override this method in a derived class. </remarks>
    ///
    /// <param name="fileNameSuffix"> A string that should be used as part of the file name (a suffix).
    /// May be empty, but not null. </param>
    ///
    /// <returns>The generated file name, for example <c>CCA.TestHooking.dtt</c>.</returns>
    protected virtual string GenerateSettingsFileName(string fileNameSuffix)
    {
        ArgumentNullException.ThrowIfNull(fileNameSuffix);

        // Better following than Assembly.GetEntryAssembly(), which may return null
        Assembly assembly = Assembly.GetExecutingAssembly().GetRootOrCurrentAssembly();
        string asmName = assembly.GetName().Name;
        string strResult = $"{asmName}{fileNameSuffix}.dtt";

        return strResult;
    }

    /// <summary> Creates the underlying <see cref="IsolatedStorageFile"/> used for reading or writing. </summary>
    ///
    /// <returns>The isolated-storage file store.</returns>
    protected virtual IsolatedStorageFile GetStorageFile()
    {
        IsolatedStorageFile isoStore = IsolatedStorageFile.GetStore(this.Scope, null, null);

        return isoStore;
    }
    #endregion // Protected methods
    #endregion // Methods
}
#pragma warning restore SYSLIB0011