//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.0.3705.0.
// 
using System.Xml.Serialization;


/// <remarks/>
[XmlTypeAttribute(Namespace = "http://example.org/xmlserializer")]
[XmlRootAttribute("paymentMethod", Namespace = "http://example.org/xmlserializer", IsNullable = false)]
public class PaymentMethod
{
  /// <remarks/>
  [XmlElementAttribute("commision", typeof(System.Double))]
  [XmlElementAttribute("hourly", typeof(System.Double))]
  [XmlElementAttribute("salary", typeof(System.Double))]
  [XmlElementAttribute("other", typeof(string))]
  [XmlChoiceIdentifierAttribute("ItemElementName")]
  public object Item;

  /// <remarks/>
  [XmlIgnoreAttribute()]
  public ItemChoiceType ItemElementName;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://example.org/xmlserializer", IncludeInSchema = false)]
public enum ItemChoiceType
{

  /// <remarks/>
  commision,

  /// <remarks/>
  hourly,

  /// <remarks/>
  salary,

  /// <remarks/>
  other,
}

/// <remarks/>
[XmlTypeAttribute(Namespace = "http://example.org/xmlserializer")]
[XmlRootAttribute("employee", Namespace = "http://example.org/xmlserializer", IsNullable = false)]
public class Employee
{
  /// <remarks/>
  public string id;

  /// <remarks/>
  public string name;

  /// <remarks/>
  [System.Xml.Serialization.XmlTextAttribute()]
  public string[] Text;
}

[XmlTypeAttribute(Namespace = "http://example.org/xmlserializer")]
[XmlRootAttribute("employee2", Namespace = "http://example.org/xmlserializer", IsNullable = false)]
public class Employee2
{
  /// <remarks/>
  [XmlAttribute]
  public string id;

  public string foo;

  /// <remarks/>
  [XmlText]
  public string name;

}
